/**
 * Compact Training Plan Zod Schema
 *
 * Runtime validation for compact training plans generated by AI models.
 */

import { z } from "zod";

// ============================================================================
// Core Types
// ============================================================================

export const SportSchema = z.enum(["swim", "bike", "run", "strength", "brick", "race", "rest"]);

export const FirstDayOfWeekSchema = z.enum(["monday", "sunday"]);

export const DistanceUnitSchema = z.enum(["km", "mi"]);

export const DayOfWeekSchema = z.enum(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]);

// ============================================================================
// Athlete Configuration
// ============================================================================

/**
 * Pace string validation - formats like "5:30/km", "8:00/mi", "1:45/100m"
 */
export const PaceStringSchema = z
  .string()
  .regex(
    /^\d{1,2}:\d{2}(\/(?:km|mi|100[my]))?$/,
    "Pace must be in format MM:SS or MM:SS/unit (e.g., '5:30/km', '8:00/mi', '1:45/100m')"
  );

/**
 * Duration string validation - formats like "30", "30min", "1:30", "90s"
 */
export const DurationStringSchema = z
  .string()
  .regex(
    /^(\d+(?::\d{2})?(?:min|s|h)?|\d+)$/,
    "Duration must be a number or format like '30min', '1:30', '90s'"
  );

export const AthletePacesSchema = z
  .object({
    // Running paces
    easy: PaceStringSchema.optional(),
    long: PaceStringSchema.optional(),
    tempo: PaceStringSchema.optional(),
    threshold: PaceStringSchema.optional(),
    marathon: PaceStringSchema.optional(),
    halfMarathon: PaceStringSchema.optional(),
    interval: PaceStringSchema.optional(),
    // Interval-specific paces
    r200: PaceStringSchema.optional(),
    r400: PaceStringSchema.optional(),
    r800: PaceStringSchema.optional(),
    r1k: PaceStringSchema.optional(),
    rMile: PaceStringSchema.optional(),
    // Cycling
    bikeFtp: z.number().positive().optional(),
    bikeEasy: z.string().optional(),
    bikeTempo: z.string().optional(),
    bikeThreshold: z.string().optional(),
    // Swimming
    swimCss: PaceStringSchema.optional(),
    swimEasy: PaceStringSchema.optional(),
    swimTempo: PaceStringSchema.optional(),
  })
  .refine(
    (paces: Record<string, unknown>) => Object.values(paces).some((v) => v !== undefined),
    "At least one pace value must be provided"
  );

export const HRZoneConfigSchema = z.object({
  lthr: z.number().int().min(100).max(220),
  maxHR: z.number().int().min(120).max(230).optional(),
  restingHR: z.number().int().min(30).max(100).optional(),
});

export const AthleteZonesSchema = z.object({
  hr: HRZoneConfigSchema.optional(),
});

export const AthleteConstraintsSchema = z.object({
  daysPerWeek: z.union([z.number().int().min(1).max(7), z.string()]).optional(),
  preferredDays: z.array(z.string()).optional(),
  maxLongRunHours: z.number().positive().optional(),
  maxLongBikeHours: z.number().positive().optional(),
  notes: z.array(z.string()).optional(),
});

export const CompactAthleteSchema = z.object({
  name: z.string().min(1),
  event: z.string().min(1),
  eventDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in ISO format: YYYY-MM-DD"),
  startDate: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "Date must be in ISO format: YYYY-MM-DD")
    .optional(),
  paces: AthletePacesSchema,
  zones: AthleteZonesSchema.optional(),
  constraints: AthleteConstraintsSchema.optional(),
  unit: DistanceUnitSchema.default("km"),
  firstDayOfWeek: FirstDayOfWeekSchema.default("monday"),
});

// ============================================================================
// Training Phases
// ============================================================================

/**
 * Week range can be "1-3" or [1, 2, 3]
 */
export const WeekRangeSchema = z.union([
  z.string().regex(/^\d+-\d+$/, "Week range must be in format 'start-end' (e.g., '1-3')"),
  z.array(z.number().int().positive()),
]);

export const CompactPhaseSchema = z.object({
  name: z.string().min(1),
  weeks: WeekRangeSchema,
  focus: z.string().min(1),
  keyWorkouts: z.array(z.string()).optional(),
});

// ============================================================================
// Weekly Schedule
// ============================================================================

/**
 * Workout reference validation.
 * Format: "template.id" or "template.id(param)" or "template.id(param1, param2)"
 */
export const WorkoutRefSchema = z
  .string()
  .regex(
    /^[a-zA-Z0-9_.]+(?:\([^)]*\))?$/,
    "Workout reference must be in format 'template' or 'template(params)' (e.g., 'easy(30)', 'intervals.400(6)')"
  );

/**
 * A day can have a single workout or multiple (for brick days).
 */
export const DayWorkoutSchema = z.union([WorkoutRefSchema, z.array(WorkoutRefSchema)]);

/**
 * Week schedule maps days to workouts.
 */
export const CompactWeekScheduleSchema = z.record(
  z.string(), // Day key: Mon, Tue, etc.
  DayWorkoutSchema
);

export const CompactWeekSchema = z.object({
  week: z.number().int().positive(),
  phase: z.string().min(1),
  focus: z.string().optional(),
  isRecoveryWeek: z.boolean().optional(),
  targetHours: z.number().positive().optional(),
  workouts: CompactWeekScheduleSchema,
});

// ============================================================================
// Assessment (Optional)
// ============================================================================

export const CompactAssessmentEntrySchema = z.object({
  sport: SportSchema,
  evidence: z.string(),
});

export const CompactAssessmentSchema = z.object({
  foundation: z
    .object({
      raceHistory: z.array(z.string()).optional(),
      peakTrainingLoad: z.number().optional(),
      foundationLevel: z.enum(["beginner", "intermediate", "advanced", "elite"]).optional(),
      yearsInSport: z.number().optional(),
    })
    .optional(),
  currentForm: z
    .object({
      weeklyVolume: z
        .object({
          total: z.number().optional(),
          swim: z.number().optional(),
          bike: z.number().optional(),
          run: z.number().optional(),
        })
        .optional(),
      longestSessions: z
        .object({
          swim: z.number().optional(),
          bike: z.number().optional(),
          run: z.number().optional(),
        })
        .optional(),
      consistency: z.number().optional(),
    })
    .optional(),
  strengths: z.array(CompactAssessmentEntrySchema).optional(),
  limiters: z.array(CompactAssessmentEntrySchema).optional(),
  constraints: z.array(z.string()).optional(),
});

// ============================================================================
// Race Strategy
// ============================================================================

export const CompactRaceStrategySchema = z.object({
  goalTime: z.string().optional(),
  pacing: z
    .object({
      swim: z.string().optional(),
      bike: z.string().optional(),
      run: z.string().optional(),
    })
    .optional(),
  nutrition: z.string().optional(),
  notes: z.array(z.string()).optional(),
});

// ============================================================================
// Complete Compact Plan
// ============================================================================

export const CompactPlanSchema = z
  .object({
    version: z.literal("2.0"),
    athlete: CompactAthleteSchema,
    assessment: CompactAssessmentSchema.optional(),
    phases: z.array(CompactPhaseSchema).min(1),
    weeks: z.array(CompactWeekSchema).min(1),
    raceStrategy: CompactRaceStrategySchema.optional(),
  })
  .refine(
    (plan: { phases: { name: string }[]; weeks: { phase: string; week: number }[] }) => {
      // Validate that all weeks reference valid phases
      const phaseNames = new Set(plan.phases.map((p: { name: string }) => p.name));
      return plan.weeks.every((w: { phase: string }) => phaseNames.has(w.phase));
    },
    {
      message: "All weeks must reference a valid phase name",
      path: ["weeks"],
    }
  )
  .refine(
    (plan: { weeks: { week: number }[] }) => {
      // Validate week numbers are sequential and start from 1
      const weekNumbers = plan.weeks
        .map((w: { week: number }) => w.week)
        .sort((a: number, b: number) => a - b);
      for (let i = 0; i < weekNumbers.length; i++) {
        if (weekNumbers[i] !== i + 1) {
          return false;
        }
      }
      return true;
    },
    {
      message: "Week numbers must be sequential starting from 1",
      path: ["weeks"],
    }
  );

// ============================================================================
// Validation Functions
// ============================================================================

export type CompactValidationResult =
  | { success: true; data: z.infer<typeof CompactPlanSchema> }
  | { success: false; errors: CompactValidationError[] };

export interface CompactValidationError {
  path: string;
  message: string;
  code: string;
}

/**
 * Validate a compact training plan against the schema.
 */
export function validateCompactPlan(data: unknown): CompactValidationResult {
  const result = CompactPlanSchema.safeParse(data);

  if (result.success) {
    return { success: true, data: result.data };
  }

  const errors: CompactValidationError[] = result.error.issues.map((issue: z.core.$ZodIssue) => ({
    path: issue.path.join("."),
    message: issue.message,
    code: issue.code,
  }));

  return { success: false, errors };
}

/**
 * Validate a compact plan and throw an error if invalid.
 */
export function validateCompactPlanOrThrow(data: unknown): z.infer<typeof CompactPlanSchema> {
  return CompactPlanSchema.parse(data);
}

/**
 * Format validation errors into a human-readable string.
 */
export function formatCompactValidationErrors(errors: CompactValidationError[]): string {
  if (errors.length === 0) return "No errors";

  const lines = errors.map((e, i) => {
    const path = e.path || "(root)";
    return `  ${i + 1}. ${path}: ${e.message}`;
  });

  return `Validation failed with ${errors.length} error(s):\n${lines.join("\n")}`;
}

// ============================================================================
// Type Exports
// ============================================================================

export type CompactPlan = z.infer<typeof CompactPlanSchema>;
export type CompactAthlete = z.infer<typeof CompactAthleteSchema>;
export type CompactPhase = z.infer<typeof CompactPhaseSchema>;
export type CompactWeek = z.infer<typeof CompactWeekSchema>;
export type CompactWeekSchedule = z.infer<typeof CompactWeekScheduleSchema>;
export type CompactRaceStrategy = z.infer<typeof CompactRaceStrategySchema>;
export type CompactAssessment = z.infer<typeof CompactAssessmentSchema>;
export type CompactAssessmentEntry = z.infer<typeof CompactAssessmentEntrySchema>;
export type AthletePaces = z.infer<typeof AthletePacesSchema>;
export type AthleteZones = z.infer<typeof AthleteZonesSchema>;
export type HRZoneConfig = z.infer<typeof HRZoneConfigSchema>;
